import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Link } from "react-router-dom";

const Privacy = () => {
  const updated = "14 May 2026";
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="pt-28 pb-24">
        <article className="container mx-auto px-6 max-w-3xl prose prose-sm prose-invert">
          <p className="text-muted-foreground text-xs tracking-[0.25em] uppercase mb-4">Legal</p>
          <h1 className="text-4xl font-extrabold text-foreground tracking-tight mb-2">Privacy Policy</h1>
          <p className="text-xs text-muted-foreground mb-10">Last updated: {updated}</p>

          <Section title="1. Who we are">
            <p>The Human Delta™ is operated by TEMR Growth (Sweden) ("we", "us"). For privacy enquiries, contact <a href="mailto:privacy@thehumandelta.com" className="underline">privacy@thehumandelta.com</a>.</p>
          </Section>

          <Section title="2. What we collect">
            <ul>
              <li><strong>Identity & contact:</strong> full name, professional role/position, email address.</li>
              <li><strong>Demographics:</strong> gender, age range, years of experience, industry.</li>
              <li><strong>Assessment responses:</strong> your answers to the 32 Performance Audit questions.</li>
              <li><strong>Payment metadata:</strong> Stripe checkout session id, payment status. Card details are processed by Stripe and never reach our servers.</li>
              <li><strong>Operational logs:</strong> request timestamps, model latency, anonymised error traces.</li>
            </ul>
            <p>Your <strong>email address is hashed (SHA-256) in your browser</strong> before any network call. The raw address is never stored on our servers or sent to third parties.</p>
          </Section>

          <Section title="3. Lawful basis (UK/EU GDPR Art. 6)">
            <p>We process your data on the basis of your <strong>explicit consent</strong>, which you give by ticking the consent box on the Performance Audit before submitting your responses. You may withdraw consent at any time (see §9).</p>
          </Section>

          <Section title="4. Why we process it">
            <ul>
              <li>To compute your TEMR™ scores and generate your Pivot Report.</li>
              <li>To deliver the report PDF and let you retrieve it again from "My Reports".</li>
              <li>To process payment via Stripe.</li>
              <li>To monitor model performance and detect abuse (operational logs only).</li>
            </ul>
          </Section>

          <Section title="5. Automated decision-making (GDPR Art. 22)">
            <p>The report is generated by an automated profiling pipeline:</p>
            <ol>
              <li>Your answers are scored deterministically across four pillars (Tactical, Emotional, Mental, Relational).</li>
              <li>A rules-based gate maps your score profile to one of twelve leadership archetypes.</li>
              <li>A large language model (Google Gemini) writes the narrative explanation around the scores and archetype.</li>
            </ol>
            <p>The output is a development tool, not a hiring, credit, legal, or medical decision. You have the right to request a <strong>human review</strong> of any report by emailing <a href="mailto:privacy@thehumandelta.com" className="underline">privacy@thehumandelta.com</a>.</p>
          </Section>

          <Section title="6. Sub-processors and international transfers">
            <p>We rely on the following sub-processors. Each receives only the data strictly required for its purpose:</p>
            <ul>
              <li><strong>Lovable Cloud</strong> (managed Supabase, EU/US) — application hosting, database, file storage. Stores your hashed email, encrypted recipient email (wiped on delivery), demographics, answers, and generated report.</li>
              <li><strong>Stripe, Inc.</strong> (US) — payment processing. Receives your billing email and payment metadata; card data is collected directly by Stripe and never touches our servers.</li>
              <li><strong>Strato AG</strong> (Germany, EU) — SMTP relay for delivering your report email. Receives your recipient email address and the report (HTML + PDF attachment) at the moment of sending.</li>
              <li><strong>Google LLC</strong> (US) — Gemini API, primary narrative generator. Receives your name, demographics, and answers inside the prompt to personalise the narrative.</li>
              <li><strong>OpenAI, L.L.C.</strong> (US) — fallback narrative model used only if Gemini is unavailable. Receives the same prompt payload as Google.</li>
              <li><strong>Anthropic, PBC</strong> (US) — fallback narrative model used only if both Gemini and OpenAI are unavailable. Receives the same prompt payload.</li>
            </ul>
            <p><strong>International transfers.</strong> Email delivery via Strato is processed inside the EU. Stripe, Google, OpenAI and Anthropic process data in the United States; those transfers rely on the European Commission's Standard Contractual Clauses (SCCs) and each provider's Data Processing Agreement.</p>
            <p><strong>No model training.</strong> All LLM calls are made via the providers' API tiers under contractual terms that prohibit using your prompts or outputs to train their foundation models.</p>
          </Section>

          <Section title="7. Retention">
            <ul>
              <li>Generated report narrative: kept for <strong>24 months</strong> so you can re-download it, then permanently deleted.</li>
              <li>Audit and transaction logs (hashed email, payment transaction id, scoring metadata): kept for <strong>24 months (2 years)</strong>, then automatically purged by a daily scheduled job in line with GDPR Art. 5(1)(e) "storage limitation".</li>
              <li>Operational logs: rolling <strong>30 days</strong>.</li>
            </ul>
          </Section>

          <Section title="8. Security">
            <p>Audit tables are protected by Row-Level Security and accessible only via signed server-side functions. Email addresses are hashed client-side. Payment card data is never seen by our servers.</p>
          </Section>

          <Section title="9. Your rights">
            <p>Under UK/EU GDPR, Brazil LGPD, India DPDP, California CCPA/CPRA and Quebec Law 25 you have the right to access, rectify, erase, restrict, port, and object to processing of your personal data, and to lodge a complaint with your local data-protection authority.</p>
            <p>To <strong>delete all data</strong> we hold for you, visit <Link to="/my-reports" className="underline">My Reports</Link> and use the "Delete my data" action, or email <a href="mailto:privacy@thehumandelta.com" className="underline">privacy@thehumandelta.com</a> from the address you used to take the audit.</p>
          </Section>

          <Section title="10. Children">
            <p>The Human Delta™ is not intended for users under 18. Do not submit data if you are below the age of majority in your jurisdiction.</p>
          </Section>

          <Section title="11. Changes">
            <p>We will post any material change to this policy on this page with an updated "Last updated" date.</p>
          </Section>
        </article>
      </main>
      <Footer />
    </div>
  );
};

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section className="mb-8">
    <h2 className="text-lg font-bold text-foreground mb-3">{title}</h2>
    <div className="text-sm text-foreground/80 font-light leading-relaxed space-y-3">{children}</div>
  </section>
);

export default Privacy;